spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: 138717

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/auth
    user: postgres
    password: 138717
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 30923567816-erg2nbq2osj7p9hrit1co1ogav2jpu58.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  secret: secretsecretsecretsecretsecretsecret
  access-token-expiration: 86400000  # 15 minutes
  refresh-token-expiration: 86400000  # 24 hours
