apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres123
  JWT_SECRET: mySecretKey1234567890123456789012345678901234567890
